# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arjit Kapoor
email: arjitkp@gmail.com
description: To learn Storytelling/To understand Computational & Generative Creativity
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://arjitkp.github.io/" # the base hostname & protocol for your site
twitter_username: arjitkapoor
github_username:  arjitkp
paginate: 5

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
encoding: UTF-8
